pool:
  name: Hosted Ubuntu 1604
  demands: java

steps:
- task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
  displayName: 'Prepare analysis on SonarCloud'
  inputs:
    SonarCloud: sudheersonar
    organization: 'sudheer-mareddy50022'
    scannerMode: CLI
    configMode: manual
    cliProjectKey: testnode
    cliProjectName: run

- task: NodeTool@0
  displayName: 'Use Node 10.x'
  inputs:
    versionSpec: 10.x

- bash: |
   npm install
   
   npm run build
   
   #npm run test
   
   
  displayName: 'Bash Script'

- task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'

- task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
  displayName: 'Publish Quality Gate Result'
